"""empty message

Revision ID: 93813ba20f32
Revises: 
Create Date: 2020-06-04 23:16:38.888619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93813ba20f32'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_name', sa.String(length=80), nullable=False),
    sa.Column('squares', sa.Integer(), nullable=True),
    sa.Column('sheeps', sa.Integer(), nullable=True),
    sa.Column('cows', sa.Integer(), nullable=True),
    sa.Column('cheeks', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('farm_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Farm')
    # ### end Alembic commands ###
